version: "2"
run:
  go: "1.24"
linters:
  default: none
  enable:
  - asasalint
  - asciicheck
  - bidichk
  - bodyclose
  #- containedctx
  - copyloopvar
  - decorder
  - dogsled
  - dupl
  - dupword
  - durationcheck
  - errcheck
  - errchkjson
  - errname
  - errorlint
  - exhaustive
  - exptostd
  - fatcontext
  - forbidigo
  - forcetypeassert
  #- gci
  - ginkgolinter
  - gocheckcompilerdirectives
  - gochecksumtype
  - goconst
  - gocritic
  - godot
  - goprintffuncname
  - gosec
  - gosmopolitan
  - govet
  - iface
  - importas
  - ineffassign
  - intrange
  - loggercheck
  - makezero
  - mirror
  - misspell
  #- mnd
  #- nakedret
  - nilerr
  - nilnesserr
  #- nilnil
  - noctx
  - nolintlint
  - nosprintfhostport
  - perfsprint
  - prealloc
  - predeclared
  - reassign
  - revive
  - rowserrcheck
  - staticcheck
  - tagliatelle
  - testifylint
  - thelper
  - tparallel
  - unconvert
  - unparam
  - unused
  - usestdlibvars
  - usetesting
  - whitespace
  settings:
    gocritic:
      enabled-tags:
      - experimental
    gosec:
      severity: medium
      confidence: medium
      concurrency: 8
    govet:
      enable:
      - shadow
    importas:
      alias:
      # Kubernetes
      - pkg: k8s.io/api/core/v1
        alias: corev1
      - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
        alias: apiextensionsv1
      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
        alias: metav1
      - pkg: k8s.io/apimachinery/pkg/api/errors
        alias: k8serrors
      - pkg: k8s.io/apimachinery/pkg/util/errors
        alias: kerrors
      - pkg: k8s.io/component-base/logs/api/v1
        alias: logsv1
      # Controller Runtime
      - pkg: sigs.k8s.io/controller-runtime
        alias: ctrl
      # IrSO
      - pkg: github.com/metal3-io/ironic-standalone-operator/api/v1alpha1
        alias: metal3api
      no-unaliased: true
    nolintlint:
      require-specific: true
      allow-unused: false
    tagliatelle:
      case:
        rules:
          json: goCamel
  exclusions:
    generated: lax
    presets:
    - comments
    - common-false-positives
    - legacy
    - std-error-handling
    rules:
    - path: test/.*.go
      text: should not use dot imports
    - linters:
      - importas
      path: cmd/main.go
      text: metal3iov1alpha1
    - linters:
      - gosec
      path: suite_test.go
      text: 'G404: Use of weak random number generator .*'
    - linters:
      - tagliatelle
      text: CIDR
    - linters:
      - tagliatelle
      text: CA
    paths:
    - zz_generated.*\.go$
    - .*conversion.*\.go$
    - third_party$
    - builtin$
    - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
  - gofmt
  - goimports
  exclusions:
    generated: lax
    paths:
    - zz_generated.*\.go$
    - .*conversion.*\.go$
    - third_party$
    - builtin$
    - examples$
