name: Functional Tests

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]

permissions: {}

jobs:
  functional-tests:
    uses: ./.github/workflows/functional.yml
    permissions:
      checks: write
      contents: read
