# runs vulnerability scans and add them to Github Security tab

name: OSV-Scanner Scan

on:
  workflow_dispatch:
  schedule:
  - cron: "36 6 * * 1"

permissions: {}

jobs:
  scan-scheduled:
    permissions:
      actions: read
      contents: read
      security-events: write # for uploading SARIF files
    if: ${{ github.repository == 'metal3-io/ironic-standalone-operator' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # v4.2.2
    - name: Calculate go version
      id: vars
      run: echo "go_version=$(make go-version)" >> "${GITHUB_OUTPUT}"
    - name: Set up Go
      uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
    - name: Install OSV Scanner
      run: go install github.com/google/osv-scanner/cmd/osv-scanner@b13f37e1a1e4cb98556c1d34cd3256a876929be1 # v1.9.1
    - name: Run OSV Scanner
      run: |
        osv-scanner scan \
          --format json --output results.json --recursive --skip-git \
          --config=<( echo "GoVersionOverride = \"${{ steps.vars.outputs.go_version }}\"" ) \
          ./
      continue-on-error: true
    - name: "Run OSV Scanner Reporter"
      uses: google/osv-scanner/actions/reporter@1e295ee11c5e107886e58bacb04228325082146f # v1.9.2
      with:
        scan-args: |-
          --output=results.sarif
          --new=results.json
          --gh-annotations=false
      continue-on-error: true
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@6bb031afdd8eb862ea3fc1848194185e076637e5 # v3.28.11
      with:
        sarif_file: results.sarif
